# .github/workflows/diagnostics_and_merge.yml (v2.0)

name: AI Diagnostics & Auto-Merge

on:
  push:
    branches:
      - 'feature/**'

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录，以便能与main分支比较

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '03frontend/package-lock.json'

      # 3. 安装前端依赖
      - name: Install Frontend Dependencies
        run: npm --prefix 03frontend install

      # 4. 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '02backend/requirements.txt'
          
      # 5. 安装后端依赖 (包括 google-generativeai)
      - name: Install Backend Dependencies
        run: |
          pip install -r 02backend/requirements.txt
          pip install google-generativeai

      # 6. 执行AI诊断脚本
      - name: Run AI Diagnostics
        id: diagnostics
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python .github/scripts/run_diagnostics.py

      # 7. 根据诊断结果决定是否合并
      - name: Auto-merge or Comment
        # 仅当上一步成功 (即status='approved') 时才尝试合并
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            console.log('✅ Diagnostics approved. Merging PR...');
            // 此处应添加真实的 GitHub API 调用来合并 PR
            // 例如：
            // const pull_request_number = context.payload.pull_request?.number;
            // if (pull_request_number) {
            //   await github.rest.pulls.merge({
            //     owner: context.repo.owner,
            //     repo: context.repo.repo,
            //     pull_number: pull_request_number
            //   });
            //   console.log(`PR #${pull_request_number} merged.`);
            // } else {
            //   console.log('Could not find PR number. Skipping merge.');
            // }
            console.log("Merge simulation complete.");


      # 8. 如果诊断失败则发表评论
      - name: Post comment on failure
        # 仅当第6步失败 (即status='rejected') 时执行
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const reason = "AI Diagnostician Rejected Changes. Reason: ${{ steps.diagnostics.outputs.reason }}";
            console.log(`❌ Diagnostics failed. Reason: ${reason}`);
            // 此处应添加真实的 GitHub API 调用来发表评论
            // 例如：
            // const pull_request_number = context.payload.pull_request?.number;
            // if (pull_request_number) {
            //   await github.rest.issues.createComment({
            //      owner: context.repo.owner,
            //      repo: context.repo.repo,
            //      issue_number: pull_request_number,
            //      body: reason
            //   });
            // }
            console.log("Comment posting simulation complete.");